version: "3"

services:
  backend:
    # Image was built in e2_3
    image: exercise-2-3/backend
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    # Image was built in e2_3
    image: exercise-2-3/frontend
    ports:
      - 5000:5000

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example

volumes:
  database:
