version: "3"

services:
  backend:
    # Image was built in e2_3
    image: exercise-2-3/backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379

  redis:
    image: redis
