version: "3.5"

services:
  backend:
    image: ml-backend
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    ports:
      - 3000:3000
    volumes:
      - model:/src/model
    depends_on:
      - training

  frontend:
    image: ml-frontend
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
      - 5000:5000

  training:
    image: ml-training
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data
volumes:
  model:
  imgs:
  data:
